name = "JuExample"
uuid = "6931ba29-5917-4460-aa14-ec2e976b1172"
authors = ["Xuefeng Luo"]
version = "0.1.0"

[compat]
julia = "1.5"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
