name = "JuExample"
uuid = "b86f6d24-fa3c-4bb8-9a02-bb4972d8d575"
authors = ["Xuefeng Luo"]
version = "0.1.0"

[compat]
julia = "1.5"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
